### ISSUE TITLE
Possibilité de réduire les groupes 

### ISSUE THREAD

**Issue by samuelpriou** [PnMercantour/Suivi-projet-Lizmap#1]
**Se laisser la possibilité de ne pas déployer le ou les groupes.**

![groupes](https://cloud.githubusercontent.com/assets/9743288/17324582/858b091c-58a7-11e6-9f6e-6fb80be30b99.jpg)

**Comment by RaphaelChochon** [comment]
Je pense qu'il faudra songer à poster cette issue directement sur le repo de LizMap. Un de ces jours :+1:

**Comment by samuelpriou** [comment]
c'est fait ici : https://github.com/3liz/lizmap-web-client/issues/349

Signature PN
------------------------------------------------------------------------
		Samuel PRIOU
Responsable de la cellule système d'information

Parc national du Mercantour
Tel : +33 (0)4 93 16 78 60 - Mobile : +33 (0)6 34 47 68 38
www.mercantour.eu <http://www.mercantour.eu>

<https://www.facebook.com/ParcnationalduMercantour> 
<https://twitter.com/mercantour> 
<https://www.youtube.com/user/MercantourTV> 
<https://www.instagram.com/pnmercantour/>


	
	Faites un geste pour l‘environnement : n‘imprimez ce message qu‘en cas 
de nécessité

**Comment by RaphaelChochon** [comment]
Effectivement la solution donnée sur l'issue (3Liz/lizmap-web-client#349) et qui renvoie vers (3Liz/lizmap-web-client#245 fonctionne.

Par exemple chez nous : 
```
rep4
  |--media
     |-- js
        |-- mon_project
            |-- extend.js
```

Qui contient : 
```
lizMap.events.on({
	uicreated: function(e) {
		$('#group-limregl td a.expander').click();
		$('#group-admin td a.expander').click();
	}
});
```

**Résultat**
![groupe](https://cloud.githubusercontent.com/assets/17319578/17357062/28fb9798-595b-11e6-9566-321478ddd818.JPG)
