### ISSUE TITLE
Ajouter des fonds de carte autres que ceux proposés dans le plugin

### ISSUE THREAD

**Issue by samuelpriou** [PnMercantour/Suivi-projet-Lizmap#3]
Ajouter des fonds de carte tuilés autres que ceux proposés dans le plugin, ex: ScanExpress de l'IGN

![fond_tms](https://cloud.githubusercontent.com/assets/9743288/17325465/0526e174-58ac-11e6-943d-442256ddbaec.jpg)

**Comment by RaphaelChochon** [comment]
L'ajout d'autres fonds de carte fonctionne enfin. Le format ECW n'est pas supporté par QGIS-Server pour une histoire de licences. 
Donc on peut les convertir en .tiff pour passer dans du libre. 
Seul problème, la taille conséquente d'un tiff et ses pyramides. Mais avec un taux de compression à 60% (compression jpg2000), on arrive au même poids que L'ECW d'origine pour une qualité correcte. 

Il faut maintenant voir pour centraliser nos fonds de cartes dans un ou plusieurs projets mère qui eux seront cachés ou accessible uniquement aux admins

**Comment by RaphaelChochon** [comment]
Le MBTiles fonctionne aussi, cela peut être une bonne solution pour l'impression.
Par contre pour celui-ci, il faut désactiver l'option de tuilage du plugin LizMap... Ce qui veut dire pas de cache serveur. Ce n'est pas forcément très grave vu qu'on ne s'en servirait que pour l'impression.

**Comment by RaphaelChochon** [comment]
Et voila de la bonne lecture concernant d'abord LizMap et les fonds : 
* http://www.forumsig.org/showthread.php/40755-Support-de-l-ECW

Et pour convertir les .ecw en .tiff et produire les pyramides sur une machine Windows avec OSGeo4W : 
* http://vivelessig.blogspot.fr/2015/08/se-liberer-du-format-proprietaire-ecw.html

**Comment by RaphaelChochon** [comment]
Les fonds de cartes (raster) les plus utilisés ont été ajoutés à un projet nommé ``cache_raster``. Ce sont ceux la qu'il faudra appeler dans les autres projets afin de profiter de la "mise en commun" du cache.
Le cache est justement en train d'être pré-généré pour tous les fonds de ce projet via cette méthode : https://github.com/3liz/lizmap-documentation/blob/master/source/admin/cache.rst#seeding
Nous générons les tuiles des niveaux de zooms de 8 à 16 (entre 60 000 et 85 000 tuiles par couche), et peut être jusqu’à 17 pour l'ortho.

Exemple d'intégration de ces fonds dans un projet quelconque : 
![image](https://cloud.githubusercontent.com/assets/17319578/17613859/c7487440-6061-11e6-91da-6ec895b62023.png)

Attention à ne pas cliquer sur la croix rouge qui supprime le cache serveur... c'est déjà assez long à les générer !
