### ISSUE TITLE
Imprimer un fond de carte tuilé (ou pas tuilé)

### ISSUE THREAD

**Issue by samuelpriou** [PnMercantour/Suivi-projet-Lizmap#4]
Pouvoir imprimer un fond de carte tuilé (ex : ign) lorsque l'on imprime une carte.

**Comment by RaphaelChochon** [comment]
Pour mémo pour moi même, lien vers la doc concernant ce point : https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#allow-printing-of-external-baselayers

**Comment by RaphaelChochon** [comment]
Impression OK voir : https://github.com/PnMercantour/Suivi-projet-Lizmap/issues/3#issuecomment-239366881
